# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('flight_no', models.UUIDField(default=uuid.uuid4, help_text='Unique number for this flight\n', primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('F', 'Full'), ('N', 'Not Open')], default='A', max_length=1)),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pythonista.Airlines')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='plane',
            name='user',
            field=models.ManyToManyField(to='pythonista.User'),
        ),
    ]
