# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='plane',
            name='destination',
            field=models.CharField(choices=[('M', 'Madurai'), ('D', 'New Delhi'), ('N', 'New York'), ('P', 'Paris'), ('S', 'Singapore'), ('C', 'Chennai')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='plane',
            name='source',
            field=models.CharField(choices=[('M', 'Madurai'), ('D', 'New Delhi'), ('N', 'New York'), ('P', 'Paris'), ('S', 'Singapore'), ('C', 'Chennai')], default='M', max_length=1),
        ),
    ]
