# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonista', '0002_auto_20171014_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='plane',
            name='destination',
            field=models.CharField(choices=[('Madurai', 'Madurai'), ('New Delhi', 'New Delhi'), ('New York', 'New York'), ('Paris', 'Paris'), ('Singapore', 'Singapore'), ('Chennai', 'Chennai')], default='Chennai', max_length=20),
        ),
        migrations.AlterField(
            model_name='plane',
            name='source',
            field=models.CharField(choices=[('Madurai', 'Madurai'), ('New Delhi', 'New Delhi'), ('New York', 'New York'), ('Paris', 'Paris'), ('Singapore', 'Singapore'), ('Chennai', 'Chennai')], default='Madurai', max_length=20),
        ),
        migrations.AddField(
            model_name='journey',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pythonista.Plane'),
        ),
    ]
